DOCSP-18456: adding a change stream page
mongodb/docs-golang pull request #113
Opened 2022-07-26 17:09 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-18456>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18456-change-stream-page/fundamentals/crud/read-operations/watch/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?

2022-07-26 22:27 UTC, mongoKart requested changes
A lot of (possibly confusing) comments, so let's plan to go over this together (you, me, and Jordan). Some structural changes to help the flow and make it task-oriented.

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +Pipeline Parameter
Issue: A reader who isn't familiar with change streams won't know what the pipeline parameter represents.

Suggestion: Rename to "Modify the Change Stream Output"

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +change stream. Format the pipeline parameter as an array of documents, with each
```suggestion
Use the pipeline parameter to modify the change stream output. Format the pipeline parameter as an array of documents, with each 
```

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +The following example opens a change stream on the ``tea`` database but only watches for
```suggestion
The following example opens a change stream on the ``tea`` database, but only watches for
```

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +"``White Peony``" in a separate shell, this code will output the following:
```suggestion
``"White Peony"`` in a separate shell, this code will output the following:
```

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +If you delete the ``tea.ratings`` document with a ``name`` value of
```suggestion
If you delete the ``tea.ratings`` document with a ``type`` value of 
```

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +Opts Parameter
Issue: Change to a task to be consistent with previous headings

Suggestion: "Modify the Behavior of the Watch() Method"

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +parameter is optional and can remain ``nil``.
Suggestion: "Use the opts parameter to modify the behavior of the ``Watch()`` method."

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +If you update the ``rating`` value of the "``Masala``" tea from ``10`` to ``9``,
```suggestion
If you update the ``rating`` value of the ``"Masala"`` tea from ``10`` to ``9``, 
```

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +Without specifying the ``FullDocument`` option, the same update operation outputs the following:
Suggestion: "If you don't specify the ``FullDocument`` option, the same update operation no longer outputs the ``fullDocument`` value."

2022-07-26 22:27 UTC, mongoKart commented on source/fundamentals/crud/read-operations/watch.txt
> +The output no longer includes the ``"fullDocument"`` value.
Suggestion: Delete

2022-08-02 21:46 UTC, jordan-smith721 approved these changes
Great job on this! LGTM

2022-08-03 14:21 UTC, merged