DOCSP-13861 replace usage example
mongodb/docs-golang pull request #23
Opened 2021-08-17 21:43 UTC by kyuan-mongodb

## Pull Request Info

Added Usage Examples > Write Operations > Replace a Document page

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13861

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13861-ReplaceUsageExample/usage-examples/replaceOne/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

2021-08-17 23:26 UTC, terakilobyte requested changes
left a suggestion that will require other changes, but it looks good!

2021-08-17 23:26 UTC, terakilobyte commented on source/includes/usage-examples/code-snippets/replace.go
> +	}
Is there a `ModifiedCount` field in the struct? If so, let's use that as it'd be more truthful that something was written.

2021-08-17 23:26 UTC, terakilobyte commented on source/usage-examples/replaceOne.txt
> +the movie:
I think we should stick with haikus now. There are a lot of other fields in a `movie` document that we don't want to show, nor overwrite.

2021-08-23 14:27 UTC, terakilobyte approved these changes
lgtm

2021-08-24 18:03 UTC, kevinAlbs approved these changes
Minor comment, but otherwise LGTM!

2021-08-24 18:09 UTC, kyuan-mongodb commented on source/includes/usage-examples/code-snippets/replace.go
> +		return
good catch, I'm not sure why I initially had it there

2021-08-24 18:13 UTC, merged