DOCSP-13866 run a command usage example
mongodb/docs-golang pull request #24
Opened 2021-08-18 22:41 UTC by kyuan-mongodb

## Pull Request Info

Added Usage Examples > Run a Command

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13866

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13866-CommandUsageExample/usage-examples/command/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

2021-08-19 21:22 UTC, biniona-mongodb requested changes
The things that made me request changes were the phrase "CLI" and that the type of the result was not listed, other wise would have approved. Looks great! After those are addressed/discussed down to approve!

2021-08-19 21:22 UTC, biniona-mongodb commented on source/usage-examples/command.txt
> +You can run commands directly on the MongoDB server CLI using the
```suggestion
You can run commands directly on your MongoDB server using the
```

Question (possible Issue): This sounds odd, as "CLI" implies a Command Line, and I don't think this is executed from a command line (I think the server just runs the command). I see this is also the phrasing in the Java Docs, however it does not seem to be the phrasing in the Node Docs or the [Mongosh docs](https://docs.mongodb.com/manual/reference/method/db.runCommand/). Can this be double checked?

2021-08-19 21:22 UTC, biniona-mongodb commented on source/usage-examples/command.txt
> +command to the ``RunCommand()`` method, which requests for statistics
```suggestion
command to the ``RunCommand()`` method, which retrieves statistics
```
Suggestion: "Requests for" sounds odd to me. Does "retrieves" fit this better?

2021-08-19 21:22 UTC, biniona-mongodb commented on source/usage-examples/command.txt
> +contain the following:
```suggestion
contain the following cursor (maybe struct?): 
```
Suggestion: Could this be more specific? I am not sure what I am looking at, and needed to consult API docs to try and figure it out.

2021-08-19 21:22 UTC, biniona-mongodb commented on source/usage-examples/command.txt
> +    The ``result`` variable may vary depending on your data set.
```suggestion
    The ``result`` variable may vary depending the contents of your collection.
```
Nit: This struck me as odd as the data set we are providing is in theory the same for everyone. I think this has more to do with the readers "collection" (specific of what is on their machine right now) than their "data set" (which in my head is the thing they downloaded from atlas the first time).

2021-08-19 21:49 UTC, biniona-mongodb approved these changes
LGTM

2021-08-19 21:49 UTC, kyuan-mongodb commented
Hi @kevinAlbs, This PR is ready for review.

2021-08-23 15:16 UTC, benjirewis approved these changes
LGTM!

2021-08-23 15:18 UTC, merged