DOCSP-43473: oidc
mongodb/docs-golang pull request #382
Opened 2024-09-12 19:06 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-43473>
Staging - 

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-09-13 16:08 UTC, mongoKart approved these changes
LGTM! awesome job. how was the process of transferring an existing page to Go?

2024-09-13 16:08 UTC, mongoKart commented on source/fundamentals/enterprise-auth.txt
> +built-in Azure support.
edit: based on the rest of the PR, looks like you've accounted for that!

2024-09-13 22:06 UTC, matthewdale requested changes

2024-09-13 22:06 UTC, matthewdale commented on source/includes/authentication/gke-callback.go
> +	}
Similar to above, custom callbacks do not use `AuthMechanismProperties`. See https://github.com/mongodb/mongo-go-driver/pull/1809 for the related example fix.

```suggestion
```

2024-09-13 22:06 UTC, matthewdale commented on source/includes/authentication/gke-callback.go
> +			AuthMechanismProperties: props,
Similar to above, custom callbacks do not use `AuthMechanismProperties`. See https://github.com/mongodb/mongo-go-driver/pull/1809 for the related example fix.

```suggestion
```

2024-09-16 14:00 UTC, rustagir commented on source/fundamentals/enterprise-auth.txt
> +	      client, err := mongo.Connect(options.Client().ApplyURI(uri))
This Pr is against the master branch of the docs, which is tracking for the v2 release. When I backport this ticket to the v1.17 branch, I'll make sure to correct that!

2024-09-16 17:12 UTC, matthewdale approved these changes
Looks good! 👍

2024-09-16 17:32 UTC, merged