DOCSP-13847 specify a query
mongodb/docs-golang pull request #69
Opened 2021-10-13 17:59 UTC by kyuan-mongodb

## Pull Request Info

Added Fundamentals > CRUD > Specify a Query

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-13847

### Snooty build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=616f0d70c13055282dad4213

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13847-CRUDQuery/fundamentals/crud/query-document/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging and workerpool job links in the PR description updated?

### If your page documents a concept, does it meet the following criteria?

- [x] Target the [Jasmin persona](https://drive.google.com/file/d/14FbBOLCVxwSP6M9BK4Nz1Ir9tzxT8_02/view)
- [x] Target the [Lucas persona](https://drive.google.com/file/d/1J2vqJxo7ldv7OP_obA9Q-avf0o_ju4Lk/view)

2021-10-14 22:57 UTC, melissamahoney-mongodb requested changes
Nice work Kailie! Mostly small style stuff :)

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +The following shows the match criteria format with literal values:
The following what? Example? Sample? Let's make this less ambiguous.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +function.
This language seems somewhat repetitive here. Maybe something like:

"The following examples use :ref:`literal values <go-literal-values>`
and :ref:`query operators <query-operators-go>` with the ``Find()``
function to return a subset of documents."

?

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +To run the examples in this guide, load these documents into the
"These documents" -- which documents? Perhaps better to say "load the sample data"?

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Can we make this more user-oriented? Do we need "the following"?

```suggestion
After you run this example, the output resembles:
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +   Literal value queries returns the same value as the ``$eq``
Verb conjugation for a plural.
```suggestion
   Literal value queries return the same value as the ``$eq``
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +Comparison operators compare the value in a document to the specified
Can we use a different word here than "compare"? Again, we want to avoid a circular definition.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Let's make this more user-oriented. Same Q about do we need "the following"?
```suggestion
After you run this example, the output resembles:
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +Logical operators expect at least 2 match criteria. They check if
1. Avoid personification. Operators don't really "expect" things.
2. We spell out the numbers one through nine :) [style guide ref](https://docs.mongodb.com/meta/style-guide/style/numbers/#numbers-versus-words)
```suggestion
Logical operators require at least two match criteria. They check if
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Same comment & Q.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +   a literal query returns the same value as the ``$and`` logical
Verb conjugation, criteria is plural.
```suggestion
   a literal query return the same value as the ``$and`` logical
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +   operator. The following query filters produce the same result:
```suggestion
   operator. For example, the following query filters produce the same result:
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Same comment and Q.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Same comment and Q.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Same comment and Q.

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +Bitwise operators convert a numeric field from a base 10 (decimal)
```suggestion
Bitwise operators convert a numeric field from a base-10 (decimal)
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +number into its base 2 (binary) number. They check whether the value in
```suggestion
number into the corresponding base-2 (binary) number. They check whether the value in
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +bits set as ``6`` (i.e. "00000110"):
Avoid Latin phrases and abbreviations, as they don't translate well and can be difficult for ESL readers.
```suggestion
bits set as ``6`` (which is "00000110"):
```

2021-10-14 22:57 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +After running this example, the output resembles the following:
Same comment and Q

2021-10-15 15:28 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +Comparison operators analyze the value in a document to the specified
Not sure "analyze to" is really right. How about "analyze against"?

```suggestion
Comparison operators analyze the value in a document against the specified
```

2021-10-15 15:29 UTC, melissamahoney-mongodb commented on source/fundamentals/crud/query-document.txt
> +a document has the same bits set as value in your match criteria.
```suggestion
a document has the same bits set as the value in your match criteria.
```

2021-10-19 18:02 UTC, matthewdale commented on source/includes/fundamentals/code-snippets/CRUD/query.go
> +				}},
Optional: The formatting of this block is a bit wonky. Consider moving one of these `}` brackets to the next line.

E.g.:
```go
filter := bson.D{
	{"$and",
		bson.A{
			bson.D{{"rating", bson.D{{"$gt", 7}}}},
			bson.D{{"rating", bson.D{{"$lte", 10}}}},
		},
	},
}
```

2021-10-19 18:29 UTC, merged